// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Aspersh Upadhyay and the Latch contributors
// Skills (ADR-031): validation, expansion, and matching agree word for word
// with the Rust gateway (packages/schemas/v1/skills, generated by its tests).
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { expand, find, label, validate } from "../src/skills.js";
import type { UiNode } from "../src/protocol.js";

const dir = new URL("../../../packages/schemas/v1/skills/", import.meta.url);
const cases = JSON.parse(readFileSync(new URL("cases.json", dir), "utf8"));
const expected = JSON.parse(readFileSync(new URL("expected.json", dir), "utf8"));
const attempt = <T>(f: () => T): { ok: T } | { error: string } => {
  try {
    return { ok: f() };
  } catch (e) {
    return { error: (e as Error).message };
  }
};

test("validation matches the Rust gateway", () => {
  const got = cases.validate.map((s: unknown) => attempt(() => validate(s)));
  assert.deepEqual(got, expected.validate);
});

test("expansion and labels match the Rust gateway", () => {
  const skill = validate(cases.skill);
  const got = cases.expand.map((c: { params: unknown }) => {
    const r = attempt(() => expand(skill, c.params));
    return "ok" in r ? { steps: r.ok, labels: r.ok.map(label) } : r;
  });
  assert.deepEqual(got, expected.expand);
});

test("matching words on the screen matches the Rust gateway", () => {
  const got = cases.find.map((c: { nodes: UiNode[]; target: string; near?: string; want: "tap" | "type" }) =>
    find(c.nodes, c.target, c.near, c.want) ?? null);
  assert.deepEqual(got, expected.find);
});
