#!/usr/bin/env bash
# Copies shared, generated inputs into servers/vercel, which Vercel deploys on
# its own (root directory = servers/vercel). CI runs this and fails on a diff.
#
#   scripts/sync-vercel.sh          write the copies
#   scripts/sync-vercel.sh --check  fail if the copies are stale
set -euo pipefail
cd "$(dirname "$0")/.."
out=servers/vercel
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

mkdir -p "$tmp/public" "$tmp/generated"
cp servers/mcp/src/admin/index.html servers/mcp/src/admin/admin.js servers/mcp/src/admin/admin.css "$tmp/public/"
{
  echo "// GENERATED by scripts/sync-vercel.sh from packages/schemas/v1/mcp/server.json. Do not edit."
  printf 'export const SERVER = %s as const;\n' "$(cat packages/schemas/v1/mcp/server.json)"
} > "$tmp/generated/contract.ts"
{
  echo "// GENERATED by scripts/sync-vercel.sh from packages/schemas/v1/policy/words.json. Do not edit."
  printf 'export const WORDS = %s as const;\n' "$(cat packages/schemas/v1/policy/words.json)"
} > "$tmp/generated/policy-words.ts"

if [ "${1:-}" = "--check" ]; then
  diff -r "$tmp/public" "$out/public" && diff -r "$tmp/generated" "$out/src/generated" \
    || { echo "servers/vercel copies are stale: run scripts/sync-vercel.sh" >&2; exit 1; }
  echo "servers/vercel copies are up to date"
else
  mkdir -p "$out/public" "$out/src/generated"
  cp "$tmp"/public/* "$out/public/"
  cp "$tmp"/generated/* "$out/src/generated/"
  echo "synced servers/vercel"
fi
